config/routes.rb
Rails.application.routes.draw do
  # refresh chat history
  root 'user_sessions#new'
  
  resources :user_sessions, only: [:new, :create]
  delete '/destroy_messages', controller:'messages', action:'destroy_all'
  resources :messages, only: [:index, :create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  validates :content, :role, :session_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password :password, validations: true
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    # If session[:user_id] is nil, set it to nil, otherwise find the user by id.
    @current_user ||= session[:user_id] && User.find_by(id: session[:user_id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :check_authenticated

  # GET /messages or /messages.json
  def index
    @messages = Message.where(session_id: session_id).order(created_at: :desc)
  end

  # TODO: Consider setting up two separate functions that initialize our chat, including system prompt. And another one that continues on an existing chat that's passed in
  # POST /messages or /messages.json
  def create
    Message.transaction do
      begin
        # Get number of messages
        chat_session = session[:chat_session]
        chat_history = session[:chat_history] || []
        num_questions = (session[:num_questions] || -1)
        # This should only happen the first time you log in and play, until you quit
        if chat_session.blank?
          questions_left = 20-num_questions
          # Open up the service session and pass in the system prompt
          chat_session = ChatService.new(initial_prompt: "You are a competitive bot that plays 20 questions with a user. 
          If #{num_questions} < 1 then you have not yet started the game, answer the user with: 
          'Let's play 20 questions! Think of something, and I will try my best to guess it within 20 questions, when you have a word let me know.'. 
          Once the user says they are ready, start asking questions. Remember you are only allowed to ask yes or no questions. 
          If #{num_questions} is between 2 and 20 then you are in a game already and you have #{questions_left} questions left. 
          Remember to check the chat history to help you narrow down what the user might be thinking of.
          Remember to start off with broader questions and once you hone into a category or topic, don't get too specific until you are pretty sure.
          Do not ask anything obscene, grotesque or anything to do with profanity or adult themes. 
          If #{num_questions}= 20 and you have not yet guessed the correct word, you lose. 
          State that you have lost and the game is over and ask them to clear the chat if they want to play another game.
          If you have guessed the correct word and #{num_questions} < 20 then state that you have won and ask them if they want to play again by clearing the chat. ")
        end
        # This should happen the first time you play, and every time you restart the game
        if chat_history.blank?
          chat_history = [chat_session.system_prompt]
          Message.all.order(:created_at).each do |msg|
            chat_history << {
              role: msg.role,
              content: msg.content
            }
          end
        end

        # Create a database record of the newest message
        user_message = Message.new(message_params)
        user_message.role = "user"
        user_message.session_id = session_id
        # Throw on failed message save - to be caught by rescue
        user_message.save!
        # Get all messages that exist in the db from the current session, loop through and insert them into our chat history variable
        chat_history << {
          role: user_message.role,
          content: user_message.content
        }
        
        # Call the chat service and pass in the chat history then add the response to the database record
        response = chat_session.call(chat_history:)
        ai_message = Message.new(role: "assistant", session_id: session_id, content: response)
        ai_message.save!
        chat_history << {
          role: ai_message.role,
          content: ai_message.content
        }
        # Increment our questions asked in session
        session[:num_questions] = num_questions.to_i + 1
        # If we get here we have successfully created a message and a reply and saved them so return to the chat screen with a fresh list of messages
        @messages = Message.where(session_id: session_id).order(created_at: :desc)
        redirect_to messages_url(@messages), notice: "Message was successfully created."
      
        # rescue failed message save and raise error, undo user message create as well
      rescue ActiveRecord::RecordInvalid
        raise ActiveRecord::Rollback
        render :new, status: :unprocessable_entity
      end
    end
  end

  # function to destroy every message in the database (clear chat history)
  def destroy_all
    Message.transaction do
      begin
        # From database get all messages and loop through each and call destroy!
        Message.all.each(&:destroy!)
        session[:num_questions] = 0
        session[:chat_history] = []
        redirect_to messages_url, notice: "Chat history has been cleared!" 
      rescue ActiveRecord::RecordNotDestroyed => invalid
        puts invalid.record.errors
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end
    # Placeholder for possible future functionality
    def session_id
      1
    end
    # Checks in our session to see if a logged in user exists
    def check_authenticated
      if current_user.blank?
        render plain: '401 Unauthorized', status: :unauthorized
      end
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:content)
    end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by(name: params[:user][:name])

    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to messages_path
    else
      flash[:alert] = "Login failed"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('robot-icon-niki-2.png') %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: message) do |form| %>
  <% if message.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>
      <ul>
        <% message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="message-input-container">
    <div>
      <%= form.text_field :content, placeholder: "Reply with Yes Or No", disabled: disabled, :cols => "100", :rows => "2", :autofocus => true  %>
    </div>
    <div>
      <%= form.submit "Answer", disabled: disabled,  :class => "eightbit-btn"%>
    </div>
  </div>
<% end %>

app/views/messages/_message.html.erb
<p id="<%= dom_id message %>" class="<%=message.role%>-card message">
  <% if message.role == "assistant"%>
    <%=  image_tag("robot-icon-niki-2.png", width: 50) %>
  <%else%>
    <%= image_tag("female-icon-niki.png", width: 50) %>
  <%end%>
  <span>
    <%=message.content%>
  </span>
</p>

app/views/messages/index.html.erb
<div class="chat-container">
  <p style="color: green;margin:0;padding:0;"><%= notice %></p> 
  <h1 class="page-title">&#128512; 20 Questions</h1>
  <h4>
    Current Count: <%= [@messages.where(role: "assistant").count - 1, 0].max%>
  </h4>
  <p class="system-card message">
    <span>
      Wanna play 20 questions? Start a chat with me and I will guess what you are thinking of.
    </span>
    <%= link_to "New Chat", destroy_messages_path, data: { "turbo-method": :delete },  :class => "eightbit-btn" %>
  </p>
  <div id="messages" class="messages-container">
    <% @messages.each do |message| %>
      <%= render message %>
    <% end %>
  </div>
  <%= render "form", message: Message.new, disabled: @messages.first&.role == "user" %>
</div>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/new.html.erb
<!-- app/views/user_sessions/new.html.erb -->
<div id='login-container'> 
<h1>Login page</h1>
<%= form_with model: @user, url: user_sessions_path do |f| %>
  <div>
    <%= f.text_field :name , :class => "login-input" , placeholder: "Username" %>
  </div>
  <h1>  </h1>
  <div>
    <%= f.password_field :password, :class => "login-input" , placeholder: "Password" %>
  </div>
  <p>
    <%= f.submit "Let's Play!",  :class => "eightbit-btn" %>
  </p>
</div>
<% end %>